name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1
      - name: test hello world
        run: |
          yarn test
